services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  seq:
    image: "docker.io/datalust/seq:2025.1"
    environment:
      ACCEPT_EULA: "Y"
      ACEPT_EULA: "Y"
    expose:
      - "80"
    networks:
      - "aspire"
  keycloak:
    image: "quay.io/keycloak/keycloak:26.2"
    command:
      - "start"
      - "--import-realm"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
      - "9000"
    volumes:
      - type: "volume"
        target: "/opt/keycloak/data"
        source: "keycloak_data"
        read_only: false
    networks:
      - "aspire"
  cache:
    image: "docker.io/library/redis:7.4"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${CACHE_PASSWORD}"
    expose:
      - "6379"
    networks:
      - "aspire"
  apiservice:
    image: "${APISERVICE_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${APISERVICE_PORT}"
      ConnectionStrings__seq: "http://seq:80"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "apiservice"
    expose:
      - "${APISERVICE_PORT}"
    depends_on:
      seq:
        condition: "service_started"
      keycloak:
        condition: "service_started"
    networks:
      - "aspire"
  webfrontend:
    image: "${WEBFRONTEND_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${WEBFRONTEND_PORT}"
      services__keycloak__http__0: "http://keycloak:8080"
      services__keycloak__management__0: "http://keycloak:9000"
      ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      services__apiservice__http__0: "http://apiservice:${APISERVICE_PORT}"
      ConnectionStrings__seq: "http://seq:80"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "webfrontend"
    ports:
      - "${WEBFRONTEND_PORT}"
    depends_on:
      keycloak:
        condition: "service_started"
      cache:
        condition: "service_started"
      apiservice:
        condition: "service_started"
      seq:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  keycloak_data:
    driver: "local"
